# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'poldichen/movie-app'

steps:

  - script: |
      docker build -f Dockerfile -t movie-image .
      docker login -u poldichen -p chen425520.
      docker push movie-image