
spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: "com/poldichen/movie/dao/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
