server:
  port: 8080

spring:
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/movie?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

mybatis:
  mapper-locations: "com/poldichen/movie/dao/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true

jwt:
  prefix: marker
  secret: 123456

logging:
  level:
    com.poldichen.movie.dao: debug