server:
  port: 8080

spring:
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/movie?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

jwt:
  prefix: marker
  secret: 123456

logging:
  level:
    com.poldichen.movie.dao: debug

movie:
  host: https://www.dc.cam
  url-resource: /ajax/uncledatoolsbyajax.php